# Generated by Django 5.2.1 on 2025-05-29 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iocrm_app.artist'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iocrm_app.project'),
        ),
    ]
