# Generated by Django 4.2.21 on 2025-05-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0003_project_agreement_project_result_project_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='status',
        ),
    ]
