# Generated by Django 4.2.21 on 2025-05-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0004_rename_type_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agreement',
            field=models.URLField(blank=True, null=True, verbose_name='договор'),
        ),
        migrations.AlterField(
            model_name='project',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='iocrm_app.artist', verbose_name='проекты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='project',
            name='song',
            field=models.CharField(max_length=200, verbose_name='песни'),
        ),
    ]
