# Generated by Django 4.2.21 on 2025-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0006_alter_artist_name_alter_project_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
