# Generated by Django 4.2.21 on 2025-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0007_artist_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
