# Generated by Django 4.2.21 on 2025-06-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0008_alter_artist_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='iocrm_app.project', verbose_name='проекты')),
            ],
        ),
    ]
