# Generated by Django 4.2.21 on 2025-06-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0009_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='landing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
