# Generated by Django 4.2.21 on 2025-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0010_artist_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_cover',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
