# Generated by Django 4.2.21 on 2025-06-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0011_release_release_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='landing',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
