# Generated by Django 4.2.21 on 2025-06-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0012_release_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
