# Generated by Django 4.2.21 on 2025-06-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iocrm_app', '0013_release_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка'),
        ),
    ]
